from __future__ import annotations
from typing import Any


def generate_markdown_report(report: dict[str, Any]) -> str:
    """
    Takes the assembled report dict from generator.py and
    returns a Markdown string ready to write to a file
    or send as a download.
    """

    debate = report["debate"]
    summary = report["summary"]
    lines: list[str] = []

    # ── Header ──────────────────────────────────────────────────
    lines.append("# DIALECTA Debate Report")
    lines.append("")
    lines.append(f"**Report ID:** {report['report_id']}")
    lines.append(f"**Generated:** {report['generated_at']}")
    lines.append("")

    # ── Debate Overview ─────────────────────────────────────────
    lines.append("## Debate Overview")
    lines.append("")
    lines.append(f"**Topic:** {debate.get('topic', 'N/A')}")
    lines.append(f"**Status:** {debate.get('status', 'N/A')}")
    lines.append(f"**Overall Winner:** {debate.get('winner', 'N/A')}")
    lines.append(f"**Quality Score:** {debate.get('quality_score', 'N/A')}")
    lines.append(f"**Started:** {debate.get('created_at', 'N/A')}")
    lines.append(f"**Completed:** {debate.get('completed_at', 'N/A')}")
    lines.append("")

    # ── Summary Statistics ──────────────────────────────────────
    lines.append("## Summary Statistics")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total Sub-Debates | {summary.get('total_sub_debates', 0)} |")
    lines.append(f"| Total Rounds | {summary.get('total_rounds', 0)} |")
    lines.append(f"| Debater A Wins | {summary.get('debater_a_wins', 0)} |")
    lines.append(f"| Debater B Wins | {summary.get('debater_b_wins', 0)} |")
    lines.append(f"| Ties | {summary.get('ties', 0)} |")
    lines.append("")

    # ── Sub-Debates ─────────────────────────────────────────────
    lines.append("## Sub-Debates")
    lines.append("")

    for i, sub in enumerate(report.get("sub_debates", []), 1):
        lines.append(f"### {i}. {sub.get('sub_topic', 'Unknown Topic')}")
        lines.append("")
        lines.append(f"**Stance A:** {sub.get('stance_a', 'N/A')}")
        lines.append(f"**Stance B:** {sub.get('stance_b', 'N/A')}")
        lines.append(f"**Winner:** {sub.get('winner', 'N/A')}")
        lines.append(f"**Rounds Run:** {sub.get('rounds_run', 0)}")
        lines.append("")

        for rnd in sub.get("rounds", []):
            lines.append(f"#### Round {rnd.get('round_number', '?')}")
            lines.append("")
            lines.append(f"**Winner:** {rnd.get('round_winner', 'N/A')}")
            lines.append(
                f"**Scores:** Debater A: {rnd.get('score_a', 'N/A')} | "
                f"Debater B: {rnd.get('score_b', 'N/A')}"
            )
            if rnd.get("key_insight"):
                lines.append(f"**Key Insight:** {rnd.get('key_insight')}")
            if rnd.get("exit_reason"):
                lines.append(f"**Exit Reason:** {rnd.get('exit_reason')}")
            lines.append("")

            for arg in rnd.get("arguments", []):
                speaker = arg.get("speaker", "Unknown").replace("_", " ").title()
                lines.append(f"**{speaker}:**")
                lines.append("")
                lines.append(f"> {arg.get('content', '')}")
                lines.append("")

    # ── Agent Events ─────────────────────────────────────────────
    agent_events = report.get("agent_events", [])
    if agent_events:
        lines.append("## Agent Events")
        lines.append("")
        lines.append("| Agent | Event Type | Details |")
        lines.append("|-------|------------|---------|")
        for event in agent_events:
            agent = event.get("agent_name", "N/A")
            etype = event.get("event_type", "N/A")
            details = str(event.get("details", ""))[:80]
            lines.append(f"| {agent} | {etype} | {details} |")
        lines.append("")

    # ── Footer ───────────────────────────────────────────────────
    lines.append("---")
    lines.append("")
    lines.append("*Generated by DIALECTA — Multi-Agent AI Debate System*")

    return "\n".join(lines)